CollectionCards/urls.py
from django.urls import path

from .views import *

app_name = 'CollectionCards'
urlpatterns = [
    path('', task, name='task'),
    path('generate/', generation, name='generate'),
    path('full_list/', CardListView.as_view(), name='full_list'),
    path('detail_card/<int:pk>/', CardDetailView.as_view(), name='detail_card'),
    path('detail_card/<int:pk>/edit_card/', CardUpdateView.as_view(), name='card_edit'),
    path('detail_card/<int:pk>/delete_card/', CardDeleteView.as_view(), name='Delete_card'),
    path('process/', card_creation, name='creation'),
    path('searching/', searching, name='list_for_search'),
    path('result/', search_result, name='search_result'),
    path('actualize/', actualize_db, name='actualize'),
    path('api/', expired_card_api_view)
]

cardsite/CollectionCards/urls.py
from django.urls import path

from .views import *

app_name = 'CollectionCards'
urlpatterns = [
    path('', task),
    path('generate/', generation, name='generate'),
    path('full_list/', CardListView.as_view(), name='full_list'),
    path('detail_card/<int:pk>/', CardDetailView.as_view(), name='detail_card'),
    path('detail_card/<int:pk>/edit_card/', CardUpdateView.as_view(), name='card_edit'),
    path('detail_card/<int:pk>/delete_card/', CardDeleteView.as_view(), name='Delete_card'),
    path('process/', card_creation),
    path('searching/', searching, name='list_for_search'),
    path('result/', search_result, name='search_result'),
    path('actualize/', actualize_db, name='actualize'),
    path('api/', expired_card_api_view)
]

cardsite/cardsite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('CollectionCards.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cardsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('CollectionCards.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

CollectionCards/forms.py
from django import forms

from .models import *


class GenerationForm(forms.Form):
    VALIDITY_CHOICES = [
        ('30', '1 month'),
        ('182', '6 months'),
        ('365', '1 year'),
    ]
    SERIES_CHOICES = [
        ('db', 'Debit'),
        ('lo', 'Loyalty'),
        ('cr', 'Credit'),
    ]
    number_of_cards = forms.IntegerField(min_value=1, max_value=1000)
    series_of_cards = forms.ChoiceField(choices=SERIES_CHOICES, )
    validity = forms.ChoiceField(choices=VALIDITY_CHOICES)


class UpdateCardForm(forms.ModelForm):
    class Meta:
        model = BonusCard
        fields = ['card_status']
        widgets = {'card_status': forms.RadioSelect()}


class DeleteCardForm(forms.ModelForm):
    class Meta:
        model = BonusCard
        fields = ['card_number']


class SearchingForm(forms.Form):
    STATUS_CHOICES = [
        ('', '- Empty -'),
        ('active', 'Active'),
        ('inactive', 'Inactive'),
        ('expired', 'Expired'),
    ]
    SERIES_CHOICES = [
        ('', '- Empty -'),
        ('db', 'Debit'),
        ('lo', 'Loyalty'),
        ('cr', 'Credit'),
    ]
    card_number = forms.CharField(required=False)
    card_series = forms.ChoiceField(choices=SERIES_CHOICES, required=False)
    date_of_issue = forms.DateTimeField(required=False)
    expiration_date = forms.DateTimeField(required=False)
    date_of_use = forms.DateTimeField(required=False)
    sum_money = forms.DecimalField(max_digits=10, decimal_places=2, required=False)
    card_status = forms.ChoiceField(choices=STATUS_CHOICES, required=False)

CollectionCards/views.py
from datetime import timedelta
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
# from django.db.models import Q
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic import UpdateView, DeleteView
from rest_framework.decorators import api_view
from rest_framework.response import Response

from .forms import *
from .models import *
from .serializers import BonusCardSerializer


def task(request):
    """Method shows initial task"""
    if "error_message" in request.session:
        del request.session["error_message"]
    return render(request, 'CollectionCards/base.html')


def generation(request):
    """Method generates form for new card generation"""
    form = GenerationForm()
    error_message = request.session["error_message"] if "error_message" in request.session else None
    return render(request, 'CollectionCards/GenerateForm.html', {'form': form, 'error_message': error_message})


def card_creation(request):
    """Method gets parameters of new cards and save new cards to database"""
    number_of_cards = request.POST['number_of_cards']
    series_of_cards = request.POST['series_of_cards']
    validity = request.POST['validity']
    try:
        number_of_cards = int(number_of_cards)
        if number_of_cards < 0 or number_of_cards > 1000:
            raise ValueError("Number is out of range")
    except:
        request.session["error_message"] = "Количество карт должно быть целым числом больше нуля"
        return redirect("CollectionCards:generate")

    for n in range(number_of_cards):
        a = BonusCard(card_series=series_of_cards,
                      date_of_issue=datetime.now(),
                      expiration_date=datetime.now() + timedelta(days=int(validity)),
                      sum_money=0,
                      card_status='active'
                      )
        a.save()
    template_vars = {'number_of_cards': number_of_cards,
                     'validity': validity,
                     'series_of_cards': series_of_cards}

    return render(request, 'CollectionCards/process.html', template_vars)


class CardListView(generic.ListView):
    """Class shows card list"""
    model = BonusCard
    queryset = BonusCard.objects.all().order_by('card_number')
    paginate_by = 20
    template_name = 'CollectionCards/card_list.html'


class CardDetailView(generic.DetailView):
    """Class shows details of one card"""
    model = BonusCard
    pk_url_kwarg = 'pk'
    template_name = 'CollectionCards/card_detail.html'
    context_object_name = 'card'

    def post(self, request, *args, **kwargs):
        a = BonusCard.objects.get(card_number=kwargs['pk'])
        if 'card_status' in request.POST:
            a.card_status = request.POST['card_status']
            a.save()
        return redirect(request.path)

    def get_context_data(self, **kwargs):
        """ Method has been overridden to add `PurchaseHistory` to the template context """
        context = super().get_context_data(**kwargs)
        ph = PurchaseHistory.objects.filter(bonus_card__card_number=self.kwargs['pk'])
        context['purr'] = ph
        return context


class CardUpdateView(UpdateView):
    """Update one card details"""
    model = BonusCard
    template_name = 'CollectionCards/card_edit.html'
    pk_url_kwarg = 'pk'
    fields = ['card_status']
    context_object_name = 'card'


class CardDeleteView(DeleteView):
    """Delete one card"""
    model = BonusCard
    template_name = 'CollectionCards/card_delete.html'
    success_url = reverse_lazy('CollectionCards:full_list')

def clear_error_mess(request):
    if "error_mess" in request.session:
        del request.session["error_mess"]

def searching(request):
    """Method shows form for card searching"""
    form = SearchingForm()
    error_mess = request.session["error_mess"] if "error_mess" in request.session else None
    result = render(request, 'CollectionCards/card_searching.html', {'form': form, 'error_mess': error_mess})
    clear_error_mess(request)
    return result

def search_result(request):
    """Method shows searching results"""
    # Getting searching parameters from the user
    if request.method == "POST":
        if request.POST['card_number']:
            try:
                card_number = int(request.POST['card_number'])
                if card_number < 0 or card_number > 1000000000000000:
                    raise ValueError("Number is out of range")
            except:
                request.session["error_mess"] = "Номер карты должен быть положительным целым числом"
                return redirect("CollectionCards:list_for_search")

        filter_kv = dict()
        filter_kv['card_number'] = request.POST['card_number']
        filter_kv['card_series'] = request.POST['card_series']
        filter_kv['card_status'] = request.POST['card_status']
        filter_kv['sum_money'] = request.POST['sum_money']

        filter_kv = {key: filter_kv[key] for key in filter_kv if filter_kv[key] != ''}

        fields = ('date_of_issue', 'expiration_date', 'date_of_use')

        for field in fields:
            post_value = request.POST[field]
            if post_value:
                try:
                    parsed_date = datetime.strptime(post_value, '%Y-%m')
                    filter_kv[field + '__year'] = parsed_date.date().year
                    filter_kv[field + '__month'] = parsed_date.date().month
                    clear_error_mess(request)
                except:
                    request.session["error_mess"] = "Дата должна иметь формат: yyyy-mm"
                    return redirect("CollectionCards:list_for_search")
        request.session['filter_kv'] = filter_kv
    else:
        filter_kv = request.session['filter_kv']
    # Pagination
    if filter_kv:
        card_list = BonusCard.objects.filter(**filter_kv).order_by('card_number')
        page_number = request.GET.get('page')
        paginator = Paginator(card_list, 20)
        try:
            page_obj = paginator.page(page_number)
        except PageNotAnInteger:
            page_obj = paginator.page(1)
        except EmptyPage:
            page_obj = paginator.page(paginator.num_pages)
    else:
        request.session["error_mess"] = "Не выбрано ни одного параметра поиска"
        return redirect("CollectionCards:list_for_search")

    return render(request, 'CollectionCards/card_list.html',
                  {'object_list': page_obj, 'page_obj': page_obj, 'paginator': paginator})


def actualize_db(request):
    """Database update (expired cards)"""
    count = BonusCard.actualize_database()
    template_vars = {'number_of_cards': count}
    return render(request, 'CollectionCards/actualise_db.html', template_vars)


@api_view(['GET', 'PATCH'])
def expired_card_api_view(request):
    """Experimental method for using rest api """
    if request.method == 'GET':
        cards = BonusCard.objects.filter(~Q(card_status="active"))
        serializer = BonusCardSerializer(cards, many=True)
        return Response({"message": "Got some data!", "data": serializer.data})
    if request.method == 'PATCH':
        return Response({"message2": "Got some ANOTHER data!", "data": request.data})
    return Response({"message": "Hello, world!"})

cardsite/CollectionCards/views.py
from datetime import timedelta
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic import UpdateView, DeleteView
from rest_framework.decorators import api_view
from rest_framework.response import Response

from .forms import *
from .models import *
from .serializers import BonusCardSerializer


def task(request):
    """Method shows initial task"""
    return render(request, 'CollectionCards/base.html')


def generation(request):
    """Method generates form for new card generation"""
    form = GenerationForm()
    return render(request, 'CollectionCards/GenerateForm.html', {'form': form})


def card_creation(request):
    """Method gets parameters of new cards and save new cards to database"""
    number_of_cards = request.POST['number_of_cards']
    series_of_cards = request.POST['series_of_cards']
    validity = request.POST['validity']

    for n in range(int(number_of_cards)):
        a = BonusCard(card_series=series_of_cards,
                      date_of_issue=datetime.now(),
                      expiration_date=datetime.now() + timedelta(days=int(validity)),
                      sum_money=0,
                      card_status='active'
                      )
        a.save()
    template_vars = {'number_of_cards': number_of_cards,
                     'validity': validity,
                     'series_of_cards': series_of_cards}

    return render(request, 'CollectionCards/process.html', template_vars)


class CardListView(generic.ListView):
    """Class shows card list"""
    model = BonusCard
    queryset = BonusCard.objects.all().order_by('card_number')
    paginate_by = 20
    template_name = 'CollectionCards/card_list.html'


class CardDetailView(generic.DetailView):
    """Class shows details of one card"""
    model = BonusCard
    pk_url_kwarg = 'pk'
    template_name = 'CollectionCards/card_detail.html'
    context_object_name = 'card'

    def post(self, request, *args, **kwargs):
        a = BonusCard.objects.get(card_number=kwargs['pk'])
        if 'card_status' in request.POST:
            a.card_status = request.POST['card_status']
            a.save()
        return redirect(request.path)

    def get_context_data(self, **kwargs):
        """ Method has been overridden to add `PurchaseHistory` to the template context """
        context = super().get_context_data(**kwargs)
        ph = PurchaseHistory.objects.filter(bonus_card__card_number=self.kwargs['pk'])
        context['purr'] = ph
        return context


class CardUpdateView(UpdateView):
    """Update one card details"""
    model = BonusCard
    template_name = 'CollectionCards/card_edit.html'
    pk_url_kwarg = 'pk'
    fields = ['card_status']
    context_object_name = 'card'


class CardDeleteView(DeleteView):
    """Delete one card"""
    model = BonusCard
    template_name = 'CollectionCards/card_delete.html'
    success_url = reverse_lazy('CollectionCards:full_list')


def searching(request):
    """Method shows form for card searching"""
    form = SearchingForm()
    return render(request, 'CollectionCards/card_searching.html', {'form': form})


def search_result(request):
    """Method shows searching results"""
    # Getting searching parameters from the user
    if request.method == "POST":
        filter_kv = dict()
        filter_kv['card_number'] = request.POST['card_number']
        filter_kv['card_series'] = request.POST['card_series']
        filter_kv['card_status'] = request.POST['card_status']
        filter_kv['sum_money'] = request.POST['sum_money']

        filter_kv = {key: filter_kv[key] for key in filter_kv if filter_kv[key] != ''}

        fields = ('date_of_issue', 'expiration_date', 'date_of_use')

        for field in fields:
            post_value = request.POST[field]
            if post_value != '':
                try:
                    parsed_date = datetime.strptime(post_value, '%Y-%m')
                    filter_kv[field + '__year'] = parsed_date.date().year
                    filter_kv[field + '__month'] = parsed_date.date().month
                except:
                    pass
        request.session['filter_kv'] = filter_kv
    else:
        filter_kv = request.session['filter_kv']
    # Pagination
    card_list = BonusCard.objects.filter(**filter_kv).order_by('card_number')
    page_number = request.GET.get('page')
    paginator = Paginator(card_list, 20)
    try:
        page_obj = paginator.page(page_number)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)

    return render(request, 'CollectionCards/card_list.html',
                  {'object_list': page_obj, 'page_obj': page_obj, 'paginator': paginator})


def actualize_db(request):
    """Database update (expired cards)"""
    count = BonusCard.actualize_database()
    template_vars = {'number_of_cards': count}
    return render(request, 'CollectionCards/actualise_db.html', template_vars)


@api_view(['GET', 'PATCH'])
def expired_card_api_view(request):
    """Experimental method for using rest api """
    if request.method == 'GET':
        cards = BonusCard.objects.filter(~Q(card_status="active"))
        serializer = BonusCardSerializer(cards, many=True)
        return Response({"message": "Got some data!", "data": serializer.data})
    if request.method == 'PATCH':
        return Response({"message2": "Got some ANOTHER data!", "data": request.data})
    return Response({"message": "Hello, world!"})

CollectionCards/templates/CollectionCards/GenerateForm.html
{% extends 'CollectionCards/base.html' %}


{% block content2 %}
<h4>Введите исходные данные для генерации</h4>
<form action="/process/" method="post">
    {% csrf_token %}
    {% if error_message %}
        <p style="color:#ff0000">{{ error_message }}</p>
    {% endif %}
    <table>
        <tr><td><label>Количество карт: </label></td><td><input type="text" min="1" max="1000" name="number_of_cards" ></td></tr>
        <tr><td><label for="series_of_cards">Серия карты:</label></td>
        <td><select name="series_of_cards">
        <option value="db">Debit</option>
        <option value="lo">Loyalty</option>
        <option value="cr">Credit</option>
            </select></td></tr>
        <tr><td><label for="validity">Срок действия:</label></td>
        <td><select name="validity">
        <option value="30">1 месяц</option>
        <option value="182">6 месяцев</option>
        <option value="365">1 год </option>
            </select></td></tr>
    </table>
<br>
    <p><input type="submit" value="Generate"></p>
</form>

{% endblock %}

CollectionCards/templates/CollectionCards/actualise_db.html
{% extends 'CollectionCards/base.html' %}

{% block title %}Actualize database{% endblock %}

{% block content3 %}
    <br>
        <h3>
            База данных актуализирована.
            Обновлен статус {{ number_of_cards }} карт.
        </h3>

    </br>

{% endblock %}

CollectionCards/templates/CollectionCards/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}Main page{% endblock %}</title>
    <link rel=stylesheet href={% static "CollectionCards/css/app.css" %}>
</head>
<body>
    <aside>
        <div id="content1">
            {% block content1 %}
                <h3>Navigation</h3>
                <ul>
                    <li><a href="/">Technical task</a></li>
                    <li><a href="{% url 'CollectionCards:generate' %}">Generate</a></li>
                    <li><a href="{% url 'CollectionCards:full_list' %}">Full List Cards</a></li>
                    <li><a href="{% url 'CollectionCards:list_for_search' %}">Search</a></li>
                    <li><a href="{% url 'CollectionCards:actualize' %}">Actualise database</a></li>
                </ul>

            {% endblock %}
        </div>
    </aside>
    <main>
        <div id="content2">
            {% block content2 %}
                <h4>Technical task</h4>
                Необходимо создать веб-приложение для управления базой данных бонусных карт.
                <p>Список полей:</p>
                <ul>
                    <li>серия карты,</li>
                    <li>номер карты,</li>
                    <li>дата выпуска карты,</li>
                    <li>дата окончания активности карты,</li>
                    <li>дата использования,</li>
                    <li>сумма,</li>
                    <li>статус карты (не активирована/активирована/просрочена).</li>
                </ul>
                <p>Функционал приложения:</p>
                <ul>
                    <li>список карт с полями: серия, номер, дата выпуска, дата окончания активности, статус</li>
                    <li>поиск по этим же полям</li>
                    <li>просмотр профиля карты с историей покупок по ней</li>
                    <li>активация/деактивация карты</li>
                    <li>удаление карты</li>
                    <li>реализовать генератор карт, с указанием серии и количества генерируемых карт,
                        а также "срок окончания активности" со значениями "1 год", "6 месяцев" "1 месяц".
                        После истечения срока активности карты, у карты проставляется статус "просрочена".
                    </li>
                </ul>
                <i>Примечание: </i>поля с датами должны содержать также и время.
            {% endblock %}
            <div id="content3">
        {% block content3 %}{% endblock %}
            </div>
        </div>
    </main>
</body>
</html>

CollectionCards/templates/CollectionCards/card_delete.html
{% extends 'CollectionCards/card_detail.html' %}

{% block title %}Delete card{% endblock %}

{% block content3 %}

<h4>Delete Card</h4>
    <p>Card with number  "{{object.card_number}}"  was deleted.</p>
    <form method="post">
        {% csrf_token %}
        <input type="submit" value="Ok" />
    </form>

{% endblock %}

CollectionCards/templates/CollectionCards/card_detail.html
{% extends 'CollectionCards/base.html' %}

{% block title %}Card Detail{% endblock %}

 {% block content2 %}
     <h3>Детальная информация о карте</h3>
     <table border="1">
         <tr><td>Номер карты:</td><td>{{ card.card_number }}</td></tr>
         <tr><td>Серия карты:</td><td>{{ card.card_series }}</td></tr>
         <tr><td>Дата выпуска:</td><td>{{ card.date_of_issue }}</td>
         <tr><td>Дата окончания:</td><td>{{ card.expiration_date }}</td>
         <tr><td>Сумма на карте:</td><td>{{ card.sum_money }}</td>
         <tr><td>Статус карты:</td><td>{{ card.card_status }}</td>
         <tr><td>Дата последнего использования:</td><td>{{ card.date_of_use }}</td></tr>
     </table>
     <table border="1">
         <h3>Операции по карте</h3>
         <tr>
             <td> Дата покупки </td>
             <td> Цена </td>
         </tr>
         {% for a in purr %}
            <tr>
                <td>{{ a.purchase_date}}</td>
                <td>{{ a.price }}</td>
            </tr>
         {% endfor %}
     </table>
 {% endblock %}  <br>

{% block content3 %}
    <br>
    <li><a href="{% url 'CollectionCards:card_edit' card.pk %}">Edit status card</a></li>
    <li><a href="{% url 'CollectionCards:Delete_card' card.pk %}">Delete card</a></li>
{% endblock %}

CollectionCards/templates/CollectionCards/card_edit.html
{% extends 'CollectionCards/card_detail.html' %}


{% block content3 %}

<h4>Edit Card</h4>

<form action="{{ card.get_absolute_url }}" method="post">
    <p><b>Choose card status</b></p>
    {% csrf_token %}
   <input type="radio" name="card_status" value="active">Active<Br>
   <input type="radio" name="card_status" value="inactive" checked="checked">Inactive<Br>
    <p><input type="submit" value="Save"></p>
</form>


{% endblock %}

CollectionCards/templates/CollectionCards/card_edited_detail.html
{% extends 'CollectionCards/card_detail.html' %}

{% block content2 %}
     <h3>Detail information about card</h3>
     <table border="1">
         <tr><td>Номер карты:</td><td>{{ card.card_number }}</td></tr>
         <tr><td>Серия карты:</td><td>{{ card.card_series }}</td></tr>
         <tr><td>Дата выпуска:</td><td>{{ card.date_of_issue }}</td>
         <tr><td>Дата окончания:</td><td>{{ card.expiration_date }}</td>
         <tr><td>Сумма на карте:</td><td>{{ card.sum_money }}</td>
         <tr><td>Статус карты:</td><td>{{ card.card_status }}</td>
         <tr><td>Дата последнего использования:</td><td>{{ card.date_of_use }}</td></tr>
     </table>
 {% endblock %}  <br>

 {% block content3 %}
     <h5>Статус карты обновлен!</h5>

 {% endblock %}

CollectionCards/templates/CollectionCards/card_list.html
{% extends 'CollectionCards/base.html' %}
{% block title %}Список карт{% endblock %}
{% block content2 %}
    <h5> Список карт </h5>
    <table border="1">
        <tr>
            <td> Номер карты</td>
            <td> Серия карты</td>
            <td> Дата выпуска</td>
            <td> Дата истечения</td>
            <td> Статус карты</td>
            <td> Дата использования</td>
            <td> Сумма</td>
        </tr>
        {% for card in object_list %}
            <tr>
                <td align="center"><a href="{{ card.get_absolute_url }}"
                                      title="Смотреть информацию о карте"> {{ card.card_number }} </a></td>
                <td align="center"> {{ card.card_series }}</td>
                <td> {{ card.date_of_issue }}</td>
                <td> {{ card.expiration_date }}</td>
                <td align="center"> {{ card.card_status }}</td>
                <td> {{ card.date_of_use }}</td>
                <td> {{ card.sum_money }}</td>
            </tr>
        {% endfor %}
    </table>
    <br>
    {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}">&lt; previous</a>
    {% endif %}
    <nav>
        {% for page in paginator.page_range %}
            {% if page_obj.number == page %}
                <b>{{ page }}</b>
            {% elif page_obj.number|add:-2 <= page and page <= page_obj.number|add:2 %}
                <a href="?page={{ page }}">{{ page }}</a>
            {% endif %}
        {% endfor %}
    </nav>
    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}"> next &gt;</a>
    {% endif %}
{% endblock %}  <br>
{% block content %}{% endblock %}

CollectionCards/templates/CollectionCards/card_searching.html
{% extends 'CollectionCards/base.html' %}
{% block title %}Search{% endblock %}

{% block content2 %}
<h4>Введите исходные данные для поиска</h4>
<form method="post" action="/result/">
    {% csrf_token %}
    <table>
    {% if error_mess %}
        <p style="color:#ff0000">{{ error_mess }}</p>
    {% endif %}
    <tr><td><label>Номер карты: </label></td><td><input type="text" name="card_number" ></td></tr>
    <tr><td><label for="card_series">Серия карты:</label></td>
        <td><select name="card_series">
        <option value="">- Empty -</option>
        <option value="db">Debit</option>
        <option value="lo">Loyalty</option>
        <option value="cr">Credit</option>
            </select></td></tr>
    <tr><td><label>Дата выпуска: </label></td><td><input type="text" name="date_of_issue" placeholder="ex. 2020-09"></td></tr>
    <tr><td><label>Дата истечения: </label></td><td><input type="text" name="expiration_date" placeholder="ex. 2020-09"></td></tr>
    <tr><td><label>Дата последнего использования: </label></td><td><input type="text" name="date_of_use" placeholder="ex. 2020-09"></td></tr>
    <tr><td><label for="card_status">Статус карты:</label></td>
        <td><select name="card_status">
        <option value="">- Empty -</option>
        <option value="active">Active</option>
        <option value="inactive">Inactive</option>
        <option value="expired">Expired</option>
            </select></td></tr>
    <tr><td><label>Сумма на карте: </label></td><td><input type="number" step="0.01" min="0" name="sum_money" placeholder="ex. 12,10"></td></tr>
    </table><br>

    <p>
        <button>Search</button>
        <button type="reset">Reset</button>
    </p>
</form>

{% endblock %}

CollectionCards/templates/CollectionCards/process.html
{% extends 'CollectionCards/base.html' %}



{% block content2 %}
<h4>Генерация прошла успешно </h4>
    Сгенерировано карт: {{number_of_cards }}<br/>
    Серия карт : {{series_of_cards}}<br/>
    Срок действия : {{validity }} дней
{% endblock %}